config/routes.rb
PogParty::Application.routes.draw do

  # # resources :players, only: [:new, :create] do
  # 	resources :pogs, only: [:new, :create, :show]
  # 	resources :games, only: [:new, :create, :show]
  # end
  resources :games
  post "games/:game_id/run_game", to: "games#run_game", as: :run_game

  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :pogs

  def init(number_of_pogs=10 )
    @number_of_pogs = number_of_pogs
    create_pogs
  end

  def create_pogs
    @number_of_pogs.times do
      self.pogs.build().save
    end
  end

  # def flip_pogs
  #   @game
  # end

  # def game_over?
  #   @game = Game.find
  #   @game.pogs.each do |pog|
  #     return false if pog.status == 'face_down'
  #   end
  #   true
  # end

  def drop_slammer
    face_up   = []
    face_down = []
    self.pogs.each do |pog|
      if [true,false].sample == true
        pog.status = 'face_up'
        face_up << pog
      else
        face_down << pog
      end
    end
    {face_up: face_up, face_down: face_down}
  end

end

app/models/pog.rb
class Pog < ActiveRecord::Base
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		# @open_games = Game.where(status: 'open')
		@game = Game.create()
		@game_id = @game.id
		@game.init
		@pog_ids = []
		@game.pogs.each {|pog| @pog_ids << pog.id}
	end

	def create # APPEARS AS BUTTON AT TOP OF INDEX
		# need to complete helper method current_player to use!
		game = Game.create(player1_id: current_player.id)
	end

	def run_game
		game_id = params[:game_id].to_i
		@game = retrive_game_object(game_id)
		pog_status = @game.drop_slammer
		render :json => pog_status
	end

	private

	def retrive_game_object(game_id)
		Game.where(id: game_id)[0]
	end

end

app/controllers/players/ omniauth_callbacks_controller.rb
class Players::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/player.rb)
    @player = Player.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @player.persisted?
      sign_in_and_redirect @player, :event => :authentication #this will throw if @player is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
  end

  def show
    @player = Player.find(params[:id])
  end
end

app/controllers/pogs_controller.rb
class PogsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/pog_helper.rb
module PogHelper
end

app/views/game/index.html.erb
<div class ="container">
  <div class="nav-bar">
    <h3 class="title"> Pog Party Bar </h3>
    <nav class ="nav">
      <a href="#"> How it Works</a>
      <a href="#"> Inventory</a>
    </nav>
  </div>
  <div class="game-panel">
    <div class='game-container'>
      <div class="game-board">

        <div id='pog-stack'>
          <div class='pog' id='0'></div>
          <div class='pog' id='1'></div>
          <div class='pog' id='2'></div>
          <div class='pog' id='3'></div>
          <div class='pog' id='4'></div>
          <div class='pog' id='5'></div>
          <div class='pog' id='6'></div>
        </div>
        <div id='stack-counter'></div>

      </div>
      <div class="slammer-container">
        <p>Slammer Container</p>
        <div class='slammer'>
          <img src="http://bit.ly/KTxSe3"/>
        </div>

        <div class='slammer'>
          <img src="http://bit.ly/KTxSe3"/>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/_index.html.erb
<!-- ORIGINALLY WAS WITH GAME#INDEX -->

<h1>Game Index</h1>
<%= button_to 'NEW GAME', games_path %>
<br><br>

<% @open_games.each do |game| %>
	Status: <%= game.status.upcase %>
	<br>
	Created At: <%= game.created_at.to_s %>
	<br>
	<button>JOIN GAME</button>
	<br><br>
<% end %>

app/views/games/_pogs.html.erb
<% @pog_ids.each do |pog_id|%>
  <%= raw("<div id=#{pog_id} class='pog'></div>") %>
<% end %>

app/views/games/index.html.erb
<div class ="container">

  <div class="nav-bar">
    <h3 class="title"> Pog Party</h3>
    <nav class ="nav">
      <img class="toggle-button" src="http://i.imgur.com/K2lUwbo.png"/>
      <a href="#"> How it Works</a>
      <a href="#"> Inventory</a>
    </nav>
  </div>
  <div class="game-panel">
    <div class='game-container'>
      <div class="game-board" id=<%= @game_id %>>
        <div class='pog-stack' id=<%=@number_of_pogs%>>
          <%= render partial: "pogs", object: @pog_ids %>
        </div>

        <div id='stack-counter'></div>

      </div>
      <div class="slammer-container">
        <p>Slammer Container</p>
        <div class='slammer'>
          <img src="http://bit.ly/KTxSe3"/>
        </div>

        <div class='slammer'>
          <img src="http://bit.ly/KTxSe3"/>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/new.html.erb
_new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PogParty</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/index.html.erb
index.html.erb

app/views/players/show.html.erb
<%= @player.name %>